### ISSUE TITLE
Tranformation of => into ⇒

### ISSUE THREAD

**Issue by DamienCassou** [humboldtux/template-diamonded#2]
Converting a source block with `=>` in it results in having `⇒` in the fodt file. This looks nice but might confuse the reader. Is it possible to deactivate this transformation?

**Comment by humboldtux** [comment]
C'est mal expliqué (n'hésite pas à le modifier), mais c'est expliqué dans le README, section **Désactivation des styles**, il faut encadrer ta chaîne de caractères par des signes **+**: pour l'échappement

```
+=>+
``` 

Utilise plutôt le français ici, on est sur un projet pour rédiger des articles en français pour un magazine français, il y a donc 100% que les personnes qui passent ici parlent français  ;-)

**Comment by DamienCassou** [comment]
Merci beaucoup. Y-a-t-il une liste des transformations effectuées ? Est-il possible de n'activer que le support de backquote pour avoir `code_em` et pas les autres transformations ?

**Comment by DamienCassou** [comment]
http://asciidoctor.org/docs/asciidoc-writers-guide/#replacements
